id: ingestion-q4
name: SecurityEvent by Computer
description: Top 25 computers by SecurityEvent volume. Identifies noisy endpoints for DCR filtering.
phase: 2
type: kql
timespan: P{deepDiveDays}D
query: |
  let _total = toscalar(SecurityEvent | where TimeGenerated > ago({deepDiveDays}d) | summarize round(sum(estimate_data_size(*)) / 1024.0 / 1024.0 / 1024.0, 4));
  let _totalServers = toscalar(SecurityEvent | where TimeGenerated > ago({deepDiveDays}d) | summarize dcount(Computer));
  SecurityEvent
  | where TimeGenerated > ago({deepDiveDays}d)
  | summarize
      EventCount = count(),
      EstimatedGB = round(sum(estimate_data_size(*)) / 1024.0 / 1024.0 / 1024.0, 4)
      by Computer
  | extend
      PercentOfTotal = iff(_total > 0, round(100.0 * EstimatedGB / _total, 1), 0.0),
      TotalServers = _totalServers
  | order by EstimatedGB desc
  | take 25
