id: ingestion-q5
name: SecurityEvent by EventID
description: Top 20 EventIDs by SecurityEvent volume. Identifies high-volume event types for DCR optimization.
phase: 2
type: kql
timespan: P{deepDiveDays}D
query: |
  let _total = toscalar(SecurityEvent | where TimeGenerated > ago({deepDiveDays}d) | summarize round(sum(estimate_data_size(*)) / 1024.0 / 1024.0 / 1024.0, 4));
  SecurityEvent
  | where TimeGenerated > ago({deepDiveDays}d)
  | summarize
      EventCount = count(),
      EstimatedGB = round(sum(estimate_data_size(*)) / 1024.0 / 1024.0 / 1024.0, 4)
      by EventID
  | extend PercentOfTotal = iff(_total > 0, round(100.0 * EstimatedGB / _total, 1), 0.0)
  | order by EstimatedGB desc
  | take 20
