id: ingestion-q6c
name: Syslog Top ProcessName by Facility
description: Top 30 ProcessName x Facility combinations by volume. Identifies filterable processes within noisy facilities.
phase: 2
type: kql
timespan: P{deepDiveDays}D
query: |
  let _total = toscalar(Syslog | where TimeGenerated > ago({deepDiveDays}d) | summarize round(sum(estimate_data_size(*)) / 1024.0 / 1024.0 / 1024.0, 4));
  Syslog
  | where TimeGenerated > ago({deepDiveDays}d)
  | summarize
      EventCount = count(),
      EstimatedGB = round(sum(estimate_data_size(*)) / 1024.0 / 1024.0 / 1024.0, 4),
      DistinctHosts = dcount(Computer)
      by Facility, ProcessName
  | extend PercentOfTotal = iff(_total > 0, round(100.0 * EstimatedGB / _total, 1), 0.0)
  | order by EstimatedGB desc, EventCount desc
  | take 30
